version: '2'

services:
  mongodb:
    image: mongo:3.6.2
    restart: always
    container_name: mongodb
    volumes:
      - ./mongo-data/:/data/db
      - ./mongo-config/:/data/configdb
    ports:
      - "27017:27017"
  scheduler:
    build: .
    restart: always
    environment:
      - VAULT_RID
      - VAULT_SID
      - VAULT_ADDR
    links:
      - mongodb
      - elastic
    expose:
      - 3001
    ports:
      - "3001:3001"
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.1.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - esdata:/usr/share/elasticsearch/data
volumes:
  esdata:
    driver: local